### PR TITLE
Feature/modulerefactoring

### PR DESCRIPTION
**Pull request by antschum**
Add module level docstrings and refactor module names.

### CODE REVIEW

**Comment by antschum** [comment]
First, I had to change something in the docs files because I changed the file names - was it okay that I pushed them? I thought they also get written and created automatically somehow..

Then, I would actually not keep cv on the same level as read_load, estimator and evaluate (previously calculate_AUC - always open for suggestions!! also thought about calculate_augur or just augur; evaluate is more general I guess..) because the user would not use it directly and its not super large. I think it might make sense to add it to evaluate. What do you think?

**Review by Zethson — APPROVED** [review]
All fine. The documentation is auto generated, but we need to tell Sphinx which files to auto generate which is why you had to change this.

I'd suggest to rename the `test_estimators.py` file to `test_estimator.py` now.

**Comment by antschum** [comment]
> All fine. The documentation is auto generated, but we need to tell Sphinx which files to auto generate which is why you had to change this.
> 
> I'd suggest to rename the `test_estimators.py` file to `test_estimator.py` now.

Okay, then Ill rename `test_estimators.py` and `test_calculate_auc.py`, and also add the contents of cv to evaluate and the contents of `test_cv.py` to `test_evaluate.py`? Or do you suggest keeping separate files?

**Comment by Zethson** [comment]
Oh sorry, forgot to comment on that. Let's merge them.  Sunday, 02 January 2022, 10:43AM +01:00 from antschum  ***@***.*** :

**Comment by antschum** [comment]
The calculate_auc test in `test_evaluate.py` is not running through because the `summary_metrics` contain different values - at least in the error message. When I run the exact same code in the python command line after running `poetry install` and it returns true for the assert statement running an error. 

`Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import scanpy as sc
>>> from math import isclose
>>> from augurpy.estimator import Params, create_estimator
>>> from augurpy.evaluate import calculate_auc, run_cross_validation
>>> from augurpy.read_load import load
>>> 
>>> sc_sim_adata = sc.read_h5ad("tests/sc_sim.h5ad")
/Users/tonia/opt/miniconda3/envs/pertpy/lib/python3.8/site-packages/anndata/_core/anndata.py:120: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
>>> sc_sim_adata = load(sc_sim_adata)
>>> estimator = create_estimator("random_forest_classifier", Params(random_state=42))
>>> adata, results = calculate_auc(
...         sc_sim_adata, n_threads=4, n_subsamples=3, classifier=estimator, random_state=42
...     )
Processing data. ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
>>> results['summary_metrics']
                  CellTypeA  CellTypeB  CellTypeC
mean_augur_score   0.433333   0.666667   0.666667
mean_auc           0.433333   0.666667   0.666667
>>> np.allclose(results["summary_metrics"].loc["mean_augur_score"].tolist(), [0.433333, 0.666667, 0.666667])
True`


While printing the `results['summary_metrics']` from the test file returns: 
`Processing data. ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
                  CellTypeA  CellTypeC  CellTypeB
mean_augur_score        0.5   0.783333   0.708333
mean_auc                0.5   0.783333   0.708333`

Before this was not an issue, so it has to have something to do with merging cv and evaluate. I thought it could have something to do with random states - but that does not really explain why the results are different if run through command line vs pytest. Do you have any ideas? One difference I see is that the cell type columns are ordered differently in the results. Will push what I have now, maybe you could take a look if you have time.

**Comment by Zethson** [comment]
I also don't really see it. But the differences are big enough that we have to investigate it. Could be an ordering issue somewhere. Are we using sets anywhere? They have no order guarantees. Maybe we need to use `OrderedDicts` somewhere?

**Comment by Zethson** [comment]
@antschum just pushed some refactorings to your branch. They don't influence this issue.

**Review by Zethson — APPROVED** [review]
LGTM. It might be a good idea to use setup and teardown functions for this test, but good enough for now.

**Pull request merged**
